init python hide:

    adv.what_args.pop('style', None)

init python in character:
    from renpy.character import Character

    angelica = Character('Sister Angelica', color='fffda9', image='angelica')
    anna = Character('Anna', color='7ad4ee', image='anna')
    annie = Character('Annie', color='ff9391', image='annie')
    anon = Character('[firstname]', color='ffffff', image='anon')
    aqua = Character('Aqua', color='79afc0')
    awesomo = Character('Dog', color='ec6528')
    becca = Character('Becca', color='ffbca8', image='becca')
    beth = Character('Beth', color='a23bb1', image='beth')
    bissette = Character('Miss Bissette', color='87a6d2', image='bissette')
    bodyguard = Character('Bodyguard', color='fefefe', image='bodyguard')
    bridget = Character('Coach Bridget', color='da3ab5', image='bridget')
    bubbles = Character('Mr. Bubbles', color='d04438', image='bubbles')
    buyer = Character('Buyer', color='9db3c4', image='pilly')
    cassie = Character('Cassie', color='d9092b')
    cat = Character('Cat', color='a5a5b4')
    cedric = Character('Cedric', color='c2643e', image='cedric')
    chad = Character('Chad', color='ffb65f', image='chad')
    chico = Character('Chico', color='8ccfdd', image='chico')
    clyde = Character('Clyde', color='dc8278')
    consuela = Character('Consuela', color='cae9ed', image='consuela')
    cow = Character('Mysterious Cow Girl', color='eccbce', image='daisy')
    crystal = Character('Crystal', color='e08faa', image='crystal')
    daisy = Character('Daisy', color='eccbce', image='daisy')
    debbie = Character('[deb_name]', color='9091d2', image='debbie')
    dewitt = Character('Miss Dewitt', color='c295d1')
    dexter = Character('Dexter', color='a3fcfe', image='dexter')
    diane = Character('Diane', color='7155d2', image='diane')
    dimitri = Character('Dimitri', color='a2998c', image='dimitri')
    earl = Character('Earl', color='ca5dd3', image='earl')
    erik = Character('Erik', color='57a43b', image='erik')
    eve = Character('Eve', color='57a3e6', image='eve')
    frank = Character('Frank', color='fefefe', image='frank')
    gamsay = Character('Chef Gamsay', color='dc8e65', image='gamsay')
    goon = Character('Goon', color='fefefe', image='goon')
    grace = Character('Grace', color='af434e', image='grace')
    harold = Character('Harold', color='edc77d', image='harold')
    helen = Character('Helen', color='dc321b')
    igor = Character('Igor', color='8a867a', image='igor')
    ivy = Character('Ivy', color='2ea6b0', image='ivy')
    iwanka = Character('Iwanka', color='faddb8', image='iwanka')
    jab = Character('Jab', color='866646', image='thug')
    jane = Character('Jane', color='b06d7e', image='jane')
    jenny = Character('[jen_name]', color='9fc6ef', image='jenny')
    jiang = Character('Jiang', color='c86159', image='jiang')
    josephine = Character('Josephine', color='3567be', image='josephine')
    judith = Character('Judith', color='a1d19a', image='judith')
    june = Character('June', color='c2e8cd')
    justin = Character('Justin', color='5c877b', image='justin')
    karl = Character('Karl', color='957daf', image='karl')
    kassy = Character('Kassy', color='3a96b2', image='kassy')
    katya = Character('Katya', color='83afb3', image='katya')
    keeves = Character('Father Keeves', color='889a52', image='keeves')
    kevin = Character('Kevin', color='80aba8', image='kevin')
    khadne = Character('Khadne', color='a8cfd1', image='khadne')
    kim = Character('Kim', color='4370bf', image='kim')
    konterina = Character('Konterina', color='a77eec')
    larry = Character('Larry', color='9692c1')
    lily = Character('Lily', color='6c8b5a', image='lily')
    liu = Character('Liu', color='e95c55', image='liu')
    lopez = Character('Lopez', color='ffb178', image='lopez')
    lucy = Character('Lucy', color='9361c8', image='lucy')
    maria = Character('Maria', color='dc663f', image='maria')
    martinez = Character('Martinez', color='f73a34', image='martinez')
    melonia = Character('Melonia', color='67828f', image='melonia')
    mia = Character('Mia', color='d6bbf0', image='mia')
    micoe = Character('Micoe', color='b76390', image='micoe')
    missy = Character('Missy', color='c990ff', image='missy')
    mrsj = Character('Mrs. Johnson', color='f78b2a')
    nadya = Character('Nadya', color='734f84', image='nadya')
    odette = Character('Odette', color='989da4', image='odette')
    okita = Character('Miss Okita', color='cfa9a9')
    pig = Character('Dog?!', color='e1a490')
    pilly = Character('Pilly', color='9db3c4', image='pilly')
    pink = Character('Pink Cyclone', color='da3ab5', image='bridget')
    player_name = Character('[firstname]', color='ffffff')
    priya = Character('Priya', color='319b90', image='priya')
    raz = Character('Raz', color='bf3031', image='raz')
    richard = Character('Richard', color='4a77c5', image='richard')
    ricky = Character('Ricky', color='c32f39', image='ricky')
    ronda = Character('Ronda', color='91c295', image='ronda')
    ross = Character('Miss Ross', color='44bfb4', image='ross')
    roxxy = Character('Roxxy', color='eb556d', image='roxxy')
    roz = Character('Roz', color='cab592', image='roz')
    rump = Character('Mayor Rump', color='ffe690', image='rump')
    sara = Character('Sara', color='e3bfd1', image='sara')
    sato = Character('Mr. Sato', color='85a2ef', image='sato')
    smith = Character('Principal Smith', color='b7aca9', image='smith')
    somrak = Character('Master Somrak', color='c0d6dc', image='somrak')
    sploosh = Character('Sploosh', color='d7795c')
    svetlana = Character('Svetlana', color='637b86', image='svetlana')
    tammy = Character('Tammy', color='f78b2a', image='tammy')
    terry = Character('Terry', color='fcc28d', image='terry')
    thief = Character('Thief', color='9692c1')
    thotbot = Character('Thotbot', color='cc4783', image='thotbot')
    tina = Character('Tina', color='ce5a6a', image='tina')
    tony = Character('Tony', color='a76687', image='tony')
    tuuku = Character('Tuuku', color='d8ad9b', image='tuuku')
    tyrone = Character('Tyrone', color='66b540', image='tyrone')
    vero = Character('Veronica', color='e5ada2', image='vero')
    yoyo = Character('Kim', color='50709e', image='yoyo')
    yumi = Character('Yumi', color='5468d9', image='yumi')

    thug = Character('Thug', color='fefefe', kind=jab)

    amelie = 'Amelie'
    emma = 'Emma'
    jon = 'Jon Gurbendy'
    olivia = 'Olivia'
    sammy = 'Sammy'
    sue = 'Sue'

    PA = _('PA')
    ffv = _('Familiar female voice')
    fmv = _('Familiar male voice')
    mans_voice = _('Mans Voice')
    random_brit = _('Random Girl with British accent')
    random_girl = _('Random Girl')
    random_guy = _('Random Guy')
    reporter1 = _('Reporter 1')
    reporter2 = _('Reporter 2')
    reporter3 = _('Reporter 3')


init python:
    unknown = '???'
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
