
image clyde 1f = im.Flip("characters/clyde/char_clyde_01.png",horizontal=True)
image clyde 2f = im.Flip("characters/clyde/char_clyde_02.png",horizontal=True)
image clyde 3f = im.Flip("characters/clyde/char_clyde_03.png",horizontal=True)
image clyde 4f = im.Flip("characters/clyde/char_clyde_04.png",horizontal=True)


image old_mia 7f = im.Flip("characters/mia/char_mia_07.png", horizontal=True)
image old_mia 8f = im.Flip("characters/mia/char_mia_08.png", horizontal=True)
image old_mia 9f = im.Flip("characters/mia/char_mia_09.png", horizontal=True)
image old_mia 10f = im.Flip("characters/mia/char_mia_10.png", horizontal=True)
image old_mia 12f = im.Flip("characters/mia/char_mia_12.png", horizontal=True)
image old_mia 30f = im.Flip("characters/mia/char_mia_30.png", horizontal=True)
image old_mia 40f = im.Flip("characters/mia/char_mia_40.png", horizontal=True)
image old_mia 41f = im.Flip("characters/mia/char_mia_41.png", horizontal=True)
image old_mia 42f = im.Flip("characters/mia/char_mia_42.png", horizontal=True)
image old_mia 43f = im.Flip("characters/mia/char_mia_43.png", horizontal=True)
image old_mia 44f = im.Flip("characters/mia/char_mia_44.png", horizontal=True)
image old_mia 45f = im.Flip("characters/mia/char_mia_45.png", horizontal=True)
image old_mia 46f = im.Flip("characters/mia/char_mia_46.png", horizontal=True)
image old_mia 47f = im.Flip("characters/mia/char_mia_47.png", horizontal=True)
image old_mia 48f = im.Flip("characters/mia/char_mia_48.png", horizontal=True)

image old_mial 1f = im.Flip("characters/mia/char_mia_labcoat_01.png", xoffset=-21, horizontal=True)


image helen 1f = im.Flip("characters/helen/char_helen_01.png", horizontal=True)
image helen 5f = im.Flip("characters/helen/char_helen_05.png", horizontal=True)
image helen 6f = im.Flip("characters/helen/char_helen_06.png", horizontal=True)
image helen 7f = im.Flip("characters/helen/char_helen_07.png", horizontal=True)
image helen 8f = im.Flip("characters/helen/char_helen_08.png", horizontal=True)
image helen 9f = im.Flip("characters/helen/char_helen_09.png", horizontal=True)
image helen 10f = im.Flip("characters/helen/char_helen_10.png", horizontal=True)
image helen 11f = im.Flip("characters/helen/char_helen_11.png", horizontal=True)


image old_harold 1f = im.Flip("characters/harold/char_harold_01.png", horizontal=True)
image old_harold 2f = im.Flip("characters/harold/char_harold_02.png", horizontal=True)
image old_harold 3f = im.Flip("characters/harold/char_harold_03.png", horizontal=True)
image old_harold 4f = im.Flip("characters/harold/char_harold_04.png", horizontal=True)
image old_harold 25f = im.Flip("characters/harold/char_harold_25.png", horizontal=True)
image old_harold 26f = im.Flip("characters/harold/char_harold_26.png", horizontal=True)


image old_debbie 1f = im.Flip("characters/debbie/char_debbie_01.png", horizontal=True)
image old_debbie 2f = im.Flip("characters/debbie/char_debbie_02.png", horizontal=True)
image old_debbie 3f = im.Flip("characters/debbie/char_debbie_03.png", horizontal=True)
image old_debbie 4bf = im.Flip("characters/debbie/char_debbie_04b.png",horizontal=True)
image old_debbie 5f = im.Flip("characters/debbie/char_debbie_05.png",horizontal=True)
image old_debbie 9bf = im.Flip("characters/debbie/char_debbie_09b.png",horizontal=True)
image old_debbie 10bf = im.Flip("characters/debbie/char_debbie_10b.png",horizontal=True)
image old_debbie 11bf = im.Flip("characters/debbie/char_debbie_11b.png",horizontal=True)
image old_debbie 13f = im.Flip( "characters/debbie/char_debbie_13.png", horizontal=True)
image old_debbie 14f = im.Flip( "characters/debbie/char_debbie_14.png", horizontal=True)
image old_debbie 14bf = im.Flip("characters/debbie/char_debbie_14b.png", horizontal=True)
image old_debbie 15f = im.Flip("characters/debbie/char_debbie_15.png", horizontal=True)
image old_debbie 16f = im.Flip("characters/debbie/char_debbie_16.png", horizontal=True)
image old_debbie 17f = im.Flip("characters/debbie/char_debbie_17.png", horizontal=True)
image old_debbie 18f = im.Flip("characters/debbie/char_debbie_18.png", horizontal=True)
image old_debbie 19f = im.Flip("characters/debbie/char_debbie_19.png", horizontal=True)
image old_debbie 20f = im.Flip("characters/debbie/char_debbie_20.png", horizontal=True)
image old_debbie 38f = im.Flip("characters/debbie/char_debbie_38.png", horizontal=True)
image old_debbie 39f = im.Flip("characters/debbie/char_debbie_39.png", horizontal=True)
image old_debbie 59f = im.Flip("characters/debbie/char_debbie_59.png", horizontal=True)
image old_debbie 60f = im.Flip("characters/debbie/char_debbie_60.png", horizontal=True)
image old_debbie 61f = im.Flip("characters/debbie/char_debbie_61.png", horizontal=True)
image old_debbie 62f = im.Flip("characters/debbie/char_debbie_62.png", horizontal=True)
image old_debbie 63f = im.Flip("characters/debbie/char_debbie_63.png", horizontal=True)
image old_debbie 63bf = im.Flip("characters/debbie/char_debbie_63b.png",horizontal=True)
image old_debbie 91f = im.Flip("characters/debbie/char_debbie_91.png", horizontal=True)
image old_debbie 92f = im.Flip("characters/debbie/char_debbie_92.png", horizontal=True)
image old_debbie 93f = im.Flip("characters/debbie/char_debbie_93.png", horizontal=True)
image old_debbie 125f = im.Flip("characters/debbie/char_debbie_125.png", horizontal=True)
image old_debbie 164f = im.Flip("characters/debbie/char_debbie_164.png", horizontal=True)
image old_debbie 164bf = im.Flip("characters/debbie/char_debbie_164b.png",horizontal=True)
image old_debbie 165f = im.Flip("characters/debbie/char_debbie_165.png", horizontal=True)
image old_debbie 165bf = im.Flip("characters/debbie/char_debbie_165b.png",horizontal=True)
image old_debbie 165cf = im.Flip("characters/debbie/char_debbie_165c.png",horizontal=True)
image old_debbie 166f = im.Flip("characters/debbie/char_debbie_166.png", horizontal=True)
image old_debbie 166bf = im.Flip("characters/debbie/char_debbie_166b.png",horizontal=True)
image old_debbie 166cf = im.Flip("characters/debbie/char_debbie_166c.png",horizontal=True)
image old_debbie 166df = im.Flip("characters/debbie/char_debbie_166d.png",horizontal=True)
image old_debbie 166ef = im.Flip("characters/debbie/char_debbie_166e.png",horizontal=True)
image old_debbie 168f = im.Flip("characters/debbie/char_debbie_168.png", horizontal=True)
image old_debbie 169f = im.Flip("characters/debbie/char_debbie_169.png", horizontal=True)
image old_debbie 169bf = im.Flip("characters/debbie/char_debbie_169b.png", horizontal=True)
image mneck 1f = im.Flip("characters/debbie/char_debbie_176.png", horizontal=True)
image old_debbie 183bf = im.Flip("characters/debbie/char_debbie_183b.png", horizontal=True)
image old_debbie 184cf = im.Flip("characters/debbie/char_debbie_184c.png", horizontal=True)
image old_debbie 184df = im.Flip("characters/debbie/char_debbie_184d.png", horizontal=True)
image old_debbie 188f = im.Flip("characters/debbie/char_debbie_188.png",xoffset=130, horizontal=True)
image old_debbie 189f = im.Flip("characters/debbie/char_debbie_189.png",xoffset=130, horizontal=True)
image old_debbie 190f = im.Flip("characters/debbie/char_debbie_190.png", horizontal=True)
image old_debbie 191f = im.Flip("characters/debbie/char_debbie_191.png", horizontal=True)
image debbie_robe 191bf = im.Flip("characters/debbie/char_debbie_191b.png",xoffset=-241,yoffset=-42, horizontal=True)
image old_debbie 192f = im.Flip("characters/debbie/char_debbie_192.png", horizontal=True)
image old_debbie 193f = im.Flip("characters/debbie/char_debbie_193.png", horizontal=True)
image player finger 193bf = im.Flip("characters/debbie/char_debbie_193b.png",xoffset=41,yoffset=-1, horizontal=True)
image debbies 194f = im.Flip("characters/debbie/char_debbie_194.png", horizontal=True)
image debbie_robe 194bf = im.Flip("characters/debbie/char_debbie_194b.png",xoffset=-268,yoffset=-42, horizontal=True)
image debbies 195f = im.Flip("characters/debbie/char_debbie_195.png", horizontal=True)
image debbie_robe 195bf = im.Flip("characters/debbie/char_debbie_195b.png",xoffset=-268,yoffset=-40, horizontal=True)
image debbies 196f = im.Flip("characters/debbie/char_debbie_196.png", horizontal=True)
image debbie_robe 196bf = im.Flip("characters/debbie/char_debbie_196b.png",xoffset=-269,yoffset=-39, horizontal=True)
image old_debbie 197f = im.Flip("characters/debbie/char_debbie_197.png",yoffset=-29, horizontal=True)
image debbie_robe 197bf = im.Flip("characters/debbie/char_debbie_197b.png",xoffset=-279,yoffset=-49, horizontal=True)
image old_debbie 197cf = im.Flip("characters/debbie/char_debbie_197c.png",yoffset=-24, horizontal=True)
image old_debbie 197df = im.Flip("characters/debbie/char_debbie_197d.png",yoffset=-24, horizontal=True)
image old_debbie 197ef = im.Flip("characters/debbie/char_debbie_197e.png",yoffset=-24, horizontal=True)
image old_debbie 197ff = im.Flip("characters/debbie/char_debbie_197f.png",yoffset=-24, horizontal=True)
image old_debbie 208f = im.Flip("characters/debbie/char_debbie_208.png", horizontal=True)
image old_debbie 222f = im.Flip("characters/debbie/char_debbie_222.png",horizontal=True)

image debbief 1f = im.Flip("characters/debbie/char_debbie_front_01.png", horizontal=True)
image debbief 2f = im.Flip("characters/debbie/char_debbie_front_02.png", horizontal=True)
image debbief 2bf = im.Flip("characters/debbie/char_debbie_front_02b.png", horizontal=True)
image debbief 3f = im.Flip("characters/debbie/char_debbie_front_03.png", horizontal=True)
image debbief 3bf = im.Flip("characters/debbie/char_debbie_front_03b.png", horizontal=True)
image debbief 4f = im.Flip("characters/debbie/char_debbie_front_04.png", horizontal=True)
image debbief 4bf = im.Flip("characters/debbie/char_debbie_front_04b.png", horizontal=True)
image debbief 4cf = im.Flip("characters/debbie/char_debbie_front_04c.png", horizontal=True)
image debbief 5flip = im.Flip("characters/debbie/char_debbie_front_05.png", horizontal=True)
image debbief 5bf = im.Flip("characters/debbie/char_debbie_front_05b.png", horizontal=True)
image debbief 5cf = im.Flip("characters/debbie/char_debbie_front_05c.png", horizontal=True)
image debbief 5df = im.Flip("characters/debbie/char_debbie_front_05d.png", horizontal=True)
image debbief 5ef = im.Flip("characters/debbie/char_debbie_front_05e.png", horizontal=True)
image debbief 5ff = im.Flip("characters/debbie/char_debbie_front_05f.png", horizontal=True)
image debbief 5gf = im.Flip("characters/debbie/char_debbie_front_05g.png", horizontal=True)
image debbief 6f = im.Flip("characters/debbie/char_debbie_front_06.png", horizontal=True)
image debbief 7f = im.Flip("characters/debbie/char_debbie_front_07.png", horizontal=True)
image debbief 7bf = im.Flip("characters/debbie/char_debbie_front_07b.png", horizontal=True)
image debbief 8flip = im.Flip("characters/debbie/char_debbie_front_08.png", horizontal=True)
image debbief 8bf = im.Flip("characters/debbie/char_debbie_front_08b.png", horizontal=True)
image debbief 8cf = im.Flip("characters/debbie/char_debbie_front_08c.png", horizontal=True)
image debbief 8df = im.Flip("characters/debbie/char_debbie_front_08d.png", horizontal=True)
image debbief 8ef = im.Flip("characters/debbie/char_debbie_front_08e.png", horizontal=True)
image debbief 8ff = im.Flip("characters/debbie/char_debbie_front_08f.png", horizontal=True)
image debbief 8gf = im.Flip("characters/debbie/char_debbie_front_08g.png", horizontal=True)
image debbief 9f = im.Flip("characters/debbie/char_debbie_front_09.png", horizontal=True)
image debbief 10f = im.Flip("characters/debbie/char_debbie_front_10.png", horizontal=True)
image debbief 11f = im.Flip("characters/debbie/char_debbie_front_11.png", horizontal=True)
image debbief 12f = im.Flip("characters/debbie/char_debbie_front_12.png", horizontal=True)

image debbiefa 1f = im.Flip("characters/debbie/char_debbie_front_arms_01.png", horizontal=True)
image debbiefa 2f = im.Flip("characters/debbie/char_debbie_front_arms_02.png", horizontal=True)
image debbiefa 3f = im.Flip("characters/debbie/char_debbie_front_arms_03.png", horizontal=True)
image debbiefa 3bf = im.Flip("characters/debbie/char_debbie_front_arms_03b.png", horizontal=True)
image debbiefa 4f = im.Flip("characters/debbie/char_debbie_front_arms_04.png", horizontal=True)
image debbiefa 5f = im.Flip("characters/debbie/char_debbie_front_arms_05.png", horizontal=True)
image debbiefa 5bf = im.Flip("characters/debbie/char_debbie_front_arms_05b.png", horizontal=True)
image debbiefa 5cf = im.Flip("characters/debbie/char_debbie_front_arms_05c.png", horizontal=True)


image old_dexter 16f = im.Flip("characters/dexter/char_dexter_16.png", horizontal=True)
image old_dexter 16bf = im.Flip("characters/dexter/char_dexter_16b.png", horizontal=True)


image old_judith 1f = im.Flip("characters/judith/char_judith_01.png", horizontal=True)
image old_judith 2f = im.Flip("characters/judith/char_judith_02.png", horizontal=True)
image old_judith 3f = im.Flip("characters/judith/char_judith_03.png", horizontal=True)
image old_judith 4f = im.Flip("characters/judith/char_judith_04.png", horizontal=True)
image old_judith 5f = im.Flip("characters/judith/char_judith_05.png", horizontal=True)
image old_judith 6f = im.Flip("characters/judith/char_judith_06.png", horizontal=True)
image old_judith 7f = im.Flip("characters/judith/char_judith_07.png", horizontal=True)
image old_judith 8f = im.Flip("characters/judith/char_judith_08.png", horizontal=True)
image old_judith 9f = im.Flip("characters/judith/char_judith_09.png", horizontal=True)
image old_judith 10f = im.Flip("characters/judith/char_judith_10.png", horizontal=True)


image old_erik 1f = im.Flip("characters/erik/char_erik_01.png", horizontal=True)
image old_erik 2f = im.Flip("characters/erik/char_erik_02.png", horizontal=True)
image old_erik 3f = im.Flip("characters/erik/char_erik_03.png", horizontal=True)
image old_erik 3bf = im.Flip("characters/erik/char_erik_03b.png", horizontal=True)
image old_erik 4f = im.Flip("characters/erik/char_erik_04.png", horizontal=True)
image old_erik 5f = im.Flip("characters/erik/char_erik_05.png", horizontal=True)
image old_erik 5bf = im.Flip("characters/erik/char_erik_05b.png", horizontal=True)
image old_erik 6f = im.Flip("characters/erik/char_erik_06.png", horizontal=True)
image old_erik 7f = im.Flip("characters/erik/char_erik_07.png", horizontal=True)
image old_erik 8f = im.Flip("characters/erik/char_erik_08.png", horizontal=True)
image old_erik 9f = im.Flip("characters/erik/char_erik_09.png", horizontal=True)
image old_erik 10f = im.Flip("characters/erik/char_erik_10.png", horizontal=True)
image old_erik 11f = im.Flip("characters/erik/char_erik_11.png", horizontal=True)
image old_erik 12f = im.Flip("characters/erik/char_erik_12.png", horizontal=True)
image old_erik 13f = im.Flip("characters/erik/char_erik_13.png", horizontal=True)
image old_erik 14f = im.Flip("characters/erik/char_erik_14.png", horizontal=True)
image old_erik 15f = im.Flip( "characters/erik/char_erik_15.png", horizontal=True)
image old_erik 15bf = im.Flip( "characters/erik/char_erik_15b.png", horizontal=True)
image old_erik 16f = im.Flip("characters/erik/char_erik_16.png", horizontal=True,xoffset=-13)
image old_erik 17f = im.Flip("characters/erik/char_erik_17.png", horizontal=True)
image old_erik 18f = im.Flip("characters/erik/char_erik_18.png", horizontal=True)
image old_erik 19f = im.Flip("characters/erik/char_erik_19.png", horizontal=True)
image old_erik 50f = im.Flip("characters/erik/char_erik_50.png", horizontal=True)
image old_erik 51f = im.Flip("characters/erik/char_erik_51.png", horizontal=True)
image old_erik 52f = im.Flip("characters/erik/char_erik_52.png", horizontal=True)
image old_erik 53f = im.Flip("characters/erik/char_erik_53.png", horizontal=True)
image old_erik 55f = im.Flip("characters/erik/char_erik_55.png", horizontal=True)
image old_erik 56f = im.Flip( "characters/erik/char_erik_56.png", horizontal=True)
image old_erik 57f = im.Flip( "characters/erik/char_erik_57.png", horizontal=True)
image old_erik 58f = im.Flip( "characters/erik/char_erik_58.png", horizontal=True)
image old_erik 59f = im.Flip("characters/erik/char_erik_59.png", horizontal=True)
image old_erik 60f = im.Flip("characters/erik/char_erik_60.png", horizontal=True)
image old_erik 64f = im.Flip("characters/erik/char_erik_64.png", horizontal=True)
image old_erik 65f = im.Flip("characters/erik/char_erik_65.png", horizontal=True)
image old_erik 66f = im.Flip("characters/erik/char_erik_66.png", horizontal=True)
image old_erik 67f = im.Flip("characters/erik/char_erik_67.png",xoffset=51, horizontal=True)
image old_erik 68f = im.Flip("characters/erik/char_erik_68.png",xoffset=51, horizontal=True)
image old_erik 69f = im.Flip("characters/erik/char_erik_69.png",xoffset=51, horizontal=True)
image old_erik 70f = im.Flip("characters/erik/char_erik_70.png",xoffset=51, horizontal=True)
image old_erik 71f = im.Flip("characters/erik/char_erik_71.png", horizontal=True)

image old_erikl 1f = im.Flip("characters/erik/char_erik_labcoat_01.png", xoffset=34, horizontal=True)


image principal 1f = im.Flip( "characters/principal/char_principal_01.png", horizontal=True)
image principal 2f = im.Flip( "characters/principal/char_principal_02.png", horizontal=True)
image principal 3f = im.Flip( "characters/principal/char_principal_03.png", horizontal=True)
image principal 4f = im.Flip( "characters/principal/char_principal_04.png", horizontal=True)
image principal 5f = im.Flip( "characters/principal/char_principal_05.png", horizontal=True)
image principal 6f = im.Flip( "characters/principal/char_principal_06.png", horizontal=True)
image principal 7f = im.Flip( "characters/principal/char_principal_07.png", horizontal=True)
image principal 8f = im.Flip( "characters/principal/char_principal_08.png", horizontal=True)
image principal 9f = im.Flip( "characters/principal/char_principal_09.png", horizontal=True)
image principal 10f = im.Flip( "characters/principal/char_principal_10.png", horizontal=True)
image principal 11f = im.Flip( "characters/principal/char_principal_11.png", horizontal=True)
image principal 12f = im.Flip( "characters/principal/char_principal_12.png", horizontal=True)
image principal 13f = im.Flip( "characters/principal/char_principal_13.png", horizontal=True)
image principal 14f = im.Flip( "characters/principal/char_principal_14.png", horizontal=True)
image principal 15f = im.Flip( "characters/principal/char_principal_15.png", horizontal=True)
image principal 16f = im.Flip( "characters/principal/char_principal_16.png", horizontal=True)
image principal 17f = im.Flip( "characters/principal/char_principal_17.png", horizontal=True)
image principal 18f = im.Flip( "characters/principal/char_principal_18.png", horizontal=True)
image principal 19f = im.Flip( "characters/principal/char_principal_19.png", horizontal=True)
image principal 20f = im.Flip( "characters/principal/char_principal_20.png", horizontal=True)
image principal 21f = im.Flip( "characters/principal/char_principal_21.png", horizontal=True)
image principal 22f = im.Flip( "characters/principal/char_principal_22.png", horizontal=True)
image principal 23f = im.Flip( "characters/principal/char_principal_23.png", horizontal=True)
image principal 24f = im.Flip( "characters/principal/char_principal_24.png", horizontal=True)
image principal 25f = im.Flip( "characters/principal/char_principal_25.png", horizontal=True)
image principal 26f = im.Flip( "characters/principal/char_principal_26.png", horizontal=True)
image principal 27f = im.Flip( "characters/principal/char_principal_27.png", horizontal=True)
image principal 28f = im.Flip( "characters/principal/char_principal_28.png", horizontal=True)
image principal 29f = im.Flip("characters/principal/char_principal_29.png",xoffset=70, horizontal=True)


image old_yumi 1f = im.Flip("characters/yumi/char_yumi_01.png", horizontal=True)
image old_yumi 2f = im.Flip("characters/yumi/char_yumi_02.png", horizontal=True)
image old_yumi 5f = im.Flip("characters/yumi/char_yumi_05.png", horizontal=True)
image old_yumi 6f = im.Flip("characters/yumi/char_yumi_06.png", horizontal=True)
image old_yumi 12f = im.Flip("characters/yumi/char_yumi_12.png", horizontal=True)
image old_yumi 13f = im.Flip("characters/yumi/char_yumi_13.png", horizontal=True)
image old_yumi 14f = im.Flip("characters/yumi/char_yumi_14.png", horizontal=True)


image old_sara 4f = im.Flip("characters/sara/char_sara_04.png", horizontal=True)
image old_sara 5f = im.Flip("characters/sara/char_sara_05.png", horizontal=True)


image tstand 1f = im.Flip("characters/terry/char_terry_standing_01.png", horizontal=True)
image tstand 2f = im.Flip("characters/terry/char_terry_standing_02.png", horizontal=True)
image tstand 3f = im.Flip("characters/terry/char_terry_standing_03.png", horizontal=True)


image titty 1f = im.Flip("characters/titty/char_titty_01.png", horizontal=True)


image mrsj 1f = im.Flip( "characters/mrsj/char_mrsj_01.png", horizontal=True)
image mrsj 2f = im.Flip( "characters/mrsj/char_mrsj_02.png", horizontal=True)
image mrsj 3f = im.Flip( "characters/mrsj/char_mrsj_03.png", horizontal=True)
image mrsj 4f = im.Flip( "characters/mrsj/char_mrsj_04.png", horizontal=True)
image mrsj 5f = im.Flip( "characters/mrsj/char_mrsj_05.png", horizontal=True)
image mrsj 6f = im.Flip( "characters/mrsj/char_mrsj_06.png", horizontal=True)
image mrsj 7f = im.Flip( "characters/mrsj/char_mrsj_07.png", horizontal=True)
image mrsj 8f = im.Flip( "characters/mrsj/char_mrsj_08.png", horizontal=True)
image mrsj 9f = im.Flip( "characters/mrsj/char_mrsj_09.png", horizontal=True)
image mrsj 10f = im.Flip( "characters/mrsj/char_mrsj_10.png", horizontal=True)
image mrsj 11f = im.Flip( "characters/mrsj/char_mrsj_11.png", horizontal=True)
image mrsj 12f = im.Flip( "characters/mrsj/char_mrsj_12.png", horizontal=True)
image mrsj 13f = im.Flip( "characters/mrsj/char_mrsj_13.png", horizontal=True)
image mrsj 14f = im.Flip( "characters/mrsj/char_mrsj_14.png", horizontal=True)
image mrsj 15f = im.Flip( "characters/mrsj/char_mrsj_15.png", horizontal=True)
image mrsj 16f = im.Flip( "characters/mrsj/char_mrsj_16.png", horizontal=True)
image mrsj 17f = im.Flip( "characters/mrsj/char_mrsj_17.png", horizontal=True)
image mrsj 18f = im.Flip( "characters/mrsj/char_mrsj_18.png", horizontal=True)
image mrsj 19f = im.Flip( "characters/mrsj/char_mrsj_19.png", horizontal=True)
image mrsj 20f = im.Flip( "characters/mrsj/char_mrsj_20.png", horizontal=True)
image mrsj 21f = im.Flip( "characters/mrsj/char_mrsj_21.png", horizontal=True)
image mrsj 22f = im.Flip( "characters/mrsj/char_mrsj_22.png", horizontal=True)
image mrsj 23f = im.Flip( "characters/mrsj/char_mrsj_23.png", horizontal=True)
image mrsj 24f = im.Flip( "characters/mrsj/char_mrsj_24.png", horizontal=True)
image mrsj 25f = im.Flip( "characters/mrsj/char_mrsj_25.png", horizontal=True)
image mrsj 26f = im.Flip( "characters/mrsj/char_mrsj_26.png", horizontal=True)
image mrsj 27f = im.Flip( "characters/mrsj/char_mrsj_27.png", horizontal=True)
image mrsj 28f = im.Flip( "characters/mrsj/char_mrsj_28.png", horizontal=True)
image mrsj 29f = im.Flip( "characters/mrsj/char_mrsj_29.png", horizontal=True)
image mrsj 30f = im.Flip( "characters/mrsj/char_mrsj_30.png", horizontal=True)
image mrsj 31f = im.Flip( "characters/mrsj/char_mrsj_31.png", horizontal=True)
image mrsj 32f = im.Flip( "characters/mrsj/char_mrsj_32.png", horizontal=True)
image mrsj 33f = im.Flip( "characters/mrsj/char_mrsj_33.png", horizontal=True)
image mrsj 34f = im.Flip( "characters/mrsj/char_mrsj_34.png", horizontal=True)
image mrsj 35f = im.Flip( "characters/mrsj/char_mrsj_35.png", horizontal=True)
image mrsj 38f = im.Flip("characters/mrsj/char_mrsj_38.png", horizontal=True)
image mrsj 49f = im.Flip("characters/mrsj/char_mrsj_49.png", horizontal=True)
image mrsj 50f = im.Flip("characters/mrsj/char_mrsj_50.png", horizontal=True)
image mrsj 52f = im.Flip("characters/mrsj/char_mrsj_52.png", horizontal=True)


image old_kevin 9bf = im.Flip("characters/kevin/char_kevin_09b.png", horizontal=True)
image old_kevin 14f = im.Flip("characters/kevin/char_kevin_14.png", horizontal=True)
image old_kevin 15f = im.Flip("characters/kevin/char_kevin_15.png", horizontal=True)
image old_kevin 16f = im.Flip("characters/kevin/char_kevin_16.png", horizontal=True)
image old_kevin 17f = im.Flip("characters/kevin/char_kevin_17.png", horizontal=True)
image old_kevin 18f = im.Flip("characters/kevin/char_kevin_18.png", horizontal=True)
image old_kevin 23f = im.Flip("characters/kevin/char_kevin_23.png", horizontal=True)
image old_kevin 24f = im.Flip("characters/kevin/char_kevin_24.png", horizontal=True)
image old_kevin 24bf = im.Flip("characters/kevin/char_kevin_24b.png", horizontal=True)
image old_kevin 32f = im.Flip("characters/kevin/char_kevin_32.png", horizontal=True)
image old_kevin 34f = im.Flip("characters/kevin/char_kevin_34.png",xoffset=41, horizontal=True)
image old_kevin 34bf = im.Flip("characters/kevin/char_kevin_34b.png",xoffset=41, horizontal=True)
image old_kevin 35f = im.Flip("characters/kevin/char_kevin_35.png", horizontal=True)
image old_kevin 36f = im.Flip("characters/kevin/char_kevin_36.png", horizontal=True)
image old_kevin 36bf = im.Flip("characters/kevin/char_kevin_36b.png", horizontal=True)
image old_kevin 43f = im.Flip("characters/kevin/char_kevin_43.png",horizontal=True)


image old_harold 1f = im.Flip( "characters/harold/char_harold_01.png", horizontal=True)
image old_harold 3f = im.Flip( "characters/harold/char_harold_03.png", horizontal=True)


image old_annie 1f = im.Flip("characters/annie/char_annie_01.png", horizontal=True)
image old_annie 2f = im.Flip("characters/annie/char_annie_02.png", horizontal=True)
image old_annie 3f = im.Flip("characters/annie/char_annie_03.png", horizontal=True)
image old_annie 4f = im.Flip("characters/annie/char_annie_04.png", horizontal=True)
image old_annie 5f = im.Flip("characters/annie/char_annie_05.png", horizontal=True)
image old_annie 6f = im.Flip("characters/annie/char_annie_06.png", horizontal=True)
image old_annie 7f = im.Flip("characters/annie/char_annie_07.png",horizontal=True)
image old_annie 8f = im.Flip( "characters/annie/char_annie_08.png", horizontal=True)
image old_annie 9f = im.Flip("characters/annie/char_annie_09.png",horizontal=True)
image old_annie 10f = im.Flip("characters/annie/char_annie_10.png",horizontal=True)
image old_annie 11f = im.Flip("characters/annie/char_annie_11.png",horizontal=True)
image old_annie 22f = im.Flip("characters/annie/char_annie_22.png", horizontal=True)
image old_annie 23f = im.Flip("characters/annie/char_annie_23.png", horizontal=True)


image ang 1f = im.Flip("characters/angelica/char_angelica_01.png", horizontal=True)
image ang 2f = im.Flip("characters/angelica/char_angelica_02.png", horizontal=True)
image ang 5f = im.Flip("characters/angelica/char_angelica_05.png", horizontal=True)
image ang 6f = im.Flip("characters/angelica/char_angelica_06.png", horizontal=True)
image ang 7f = im.Flip("characters/angelica/char_angelica_07.png", horizontal=True)
image ang 8f = im.Flip("characters/angelica/char_angelica_08.png", horizontal=True)
image ang 9f = im.Flip("characters/angelica/char_angelica_09.png", horizontal=True)
image ang 10f = im.Flip("characters/angelica/char_angelica_10.png", horizontal=True)
image ang 17f = im.Flip("characters/angelica/char_angelica_17.png", horizontal=True)
image ang 18f = im.Flip("characters/angelica/char_angelica_18.png", horizontal=True)
image ang 21f = im.Flip("characters/angelica/char_angelica_21.png", horizontal=True)
image ang 22f = im.Flip("characters/angelica/char_angelica_22.png", horizontal=True)
image ang 23f = im.Flip("characters/angelica/char_angelica_23.png", horizontal=True)
image ang 24f = im.Flip("characters/angelica/char_angelica_24.png", horizontal=True)
image ang 25f = im.Flip("characters/angelica/char_angelica_25.png", horizontal=True)
image ang 25bf = im.Flip("characters/angelica/char_angelica_25b.png", horizontal=True)
image ang 26f = im.Flip("characters/angelica/char_angelica_26.png", horizontal=True)
image ang 26bf = im.Flip("characters/angelica/char_angelica_26b.png", horizontal=True)
image ang 33f = im.Flip("characters/angelica/char_angelica_33.png", horizontal=True)
image ang 34f = im.Flip("characters/angelica/char_angelica_34.png", horizontal=True)
image helen whip 3 = im.Flip("characters/angelica/char_angelica_21.png", horizontal=True)


image old_anna 4f = im.Flip( "characters/anna/char_anna_04.png", horizontal=True)
image old_anna 5f = im.Flip( "characters/anna/char_anna_05.png", horizontal=True)
image old_anna 8f = im.Flip( "characters/anna/char_anna_08.png", horizontal=True)
image old_anna 12f = im.Flip( "characters/anna/char_anna_12.png", horizontal=True)


image old_becca 1f = im.Flip("characters/becca/char_becca_01.png", horizontal=True)
image old_becca 2f = im.Flip("characters/becca/char_becca_02.png", horizontal=True)
image old_becca 2bf = im.Flip("characters/becca/char_becca_02b.png", horizontal=True)
image old_becca 3f = im.Flip("characters/becca/char_becca_03.png", horizontal=True)
image old_becca 3bf = im.Flip("characters/becca/char_becca_03b.png", horizontal=True)
image old_becca 4f = im.Flip("characters/becca/char_becca_04.png", horizontal=True)
image old_becca 5f = im.Flip("characters/becca/char_becca_05.png", horizontal=True)
image old_becca 6f = im.Flip("characters/becca/char_becca_06.png", horizontal=True)
image old_becca 7f = im.Flip("characters/becca/char_becca_07.png", horizontal=True)
image old_becca 8f = im.Flip("characters/becca/char_becca_08.png", horizontal=True)
image old_becca 12f = im.Flip("characters/becca/char_becca_12.png", horizontal=True)
image old_becca 13f = im.Flip("characters/becca/char_becca_13.png", horizontal=True)
image old_becca 19f = im.Flip("characters/becca/char_becca_19.png", horizontal=True)
image old_becca 20f = im.Flip("characters/becca/char_becca_20.png", horizontal=True)
image old_becca 21f = im.Flip("characters/becca/char_becca_21.png", horizontal=True)
image old_becca 22f = im.Flip("characters/becca/char_becca_22.png", horizontal=True)
image old_becca 23f = im.Flip("characters/becca/char_becca_23.png", horizontal=True)

image old_becca front sitting 1f = im.Flip("characters/becca/char_becca_front_01.png",xoffset=-190, horizontal=True)
image old_becca front sitting 2f = im.Flip("characters/becca/char_becca_front_02.png",xoffset=-190, horizontal=True)
image old_becca front sitting 3f = im.Flip("characters/becca/char_becca_front_03.png",xoffset=-145, horizontal=True)
image old_becca front sitting 3bf = im.Flip("characters/becca/char_becca_front_03b.png",xoffset=-145, horizontal=True)

image old_becca bikini 1f = im.Flip("characters/becca/char_becca_bikini_01.png", horizontal=True)
image old_becca bikini 1bf = im.Flip("characters/becca/char_becca_bikini_01b.png", horizontal=True)
image old_becca bikini 2f = im.Flip("characters/becca/char_becca_bikini_02.png", horizontal=True)
image old_becca bikini 2bf = im.Flip("characters/becca/char_becca_bikini_02b.png", horizontal=True)
image old_becca bikini 11f = im.Flip("characters/becca/char_becca_bikini_11.png", horizontal=True)
image old_becca bikini 12f = im.Flip("characters/becca/char_becca_bikini_12.png", horizontal=True)
image old_becca bikini 17f = im.Flip("characters/becca/char_becca_bikini_17.png", horizontal=True)

image beccas_beach_sidef = im.Flip("characters/becca/char_becca_sex_foursome_side.png", horizontal=True)


image old_missy 1f = im.Flip("characters/missy/char_missy_01.png", horizontal=True)
image old_missy 1bf = im.Flip("characters/missy/char_missy_01b.png", horizontal=True)
image old_missy 2f = im.Flip("characters/missy/char_missy_02.png", horizontal=True)
image old_missy 2bf = im.Flip("characters/missy/char_missy_02b.png", horizontal=True)
image old_missy 3f = im.Flip("characters/missy/char_missy_03.png", horizontal=True)
image old_missy 4f = im.Flip("characters/missy/char_missy_04.png", horizontal=True)
image old_missy 4bf = im.Flip("characters/missy/char_missy_04b.png", horizontal=True)
image old_missy 4cf = im.Flip("characters/missy/char_missy_04c.png", horizontal=True)
image old_missy 6f = im.Flip("characters/missy/char_missy_06.png", horizontal=True)
image old_missy 7f = im.Flip("characters/missy/char_missy_07.png", horizontal=True)
image old_missy 8f = im.Flip("characters/missy/char_missy_08.png", horizontal=True)

image old_missy naked 1f = im.Flip("characters/missy/char_missy_naked_01.png", horizontal=True)
image old_missy naked 2f = im.Flip("characters/missy/char_missy_naked_02.png", horizontal=True)
image old_missy naked 3f = im.Flip("characters/missy/char_missy_naked_03.png",xoffset=5, horizontal=True)
image old_missy naked 4f = im.Flip("characters/missy/char_missy_naked_04.png", horizontal=True)
image old_missy naked 5f = im.Flip("characters/missy/char_missy_naked_05.png", horizontal=True)
image old_missy naked 6f = im.Flip("characters/missy/char_missy_naked_06.png", horizontal=True)
image old_missy naked 7f = im.Flip("characters/missy/char_missy_naked_07.png", horizontal=True)

image old_missy front sitting 1f = im.Flip("characters/missy/char_missy_front_01.png",xoffset=-170, horizontal=True)
image old_missy front sitting 2f = im.Flip("characters/missy/char_missy_front_02.png",xoffset=-170, horizontal=True)
image old_missy front sitting 3f = im.Flip("characters/missy/char_missy_front_03.png",xoffset=-134, horizontal=True)
image old_missy front sitting 3bf = im.Flip("characters/missy/char_missy_front_03b.png",xoffset=-134, horizontal=True)

image old_missy_arm front sitting 1f = im.Flip("characters/missy/char_missy_front_arms_01.png",xoffset=-156,yoffset=-375, horizontal=True)

image old_missy bikini 1f = im.Flip("characters/missy/char_missy_bikini_01.png", horizontal=True)
image old_missy bikini 2f = im.Flip("characters/missy/char_missy_bikini_02.png", horizontal=True)

image missys_beach_sidef = im.Flip("characters/missy/char_missy_sex_foursome_side.png", horizontal=True)


image teacher 1f = im.Flip("characters/teacher/char_teacher_01.png", horizontal=True)
image teacher 2f = im.Flip("characters/teacher/char_teacher_02.png", horizontal=True)
image teacher 3f = im.Flip("characters/teacher/char_teacher_03.png", horizontal=True)
image teacher 4f = im.Flip("characters/teacher/char_teacher_04.png", horizontal=True)
image teacher 5f = im.Flip("characters/teacher/char_teacher_05.png", horizontal=True)
image teacher 6bf = im.Flip("characters/teacher/char_teacher_06b.png", horizontal=True)
image teacher 7f = im.Flip("characters/teacher/char_teacher_07.png", horizontal=True)
image teacher 12f = im.Flip("characters/teacher/char_teacher_12.png", horizontal=True)
image teacher 18f = im.Flip("characters/teacher/char_teacher_18.png", horizontal=True)
image teacher 19f = im.Flip("characters/teacher/char_teacher_19.png", horizontal=True)
image teacher 20f = im.Flip("characters/teacher/char_teacher_20.png", horizontal=True)
image teacher 24bf = im.Flip("characters/teacher/char_teacher_24b.png", horizontal=True)
image teacher 24cf = im.Flip("characters/teacher/char_teacher_24c.png", horizontal=True)


image june 9f = im.Flip("characters/june/char_june_09.png", horizontal=True)
image june 10f = im.Flip("characters/june/char_june_10.png", horizontal=True)


image old_roxxy 1f f = im.Flip("characters/roxxy/char_roxxy_01.png", horizontal=True)
image old_roxxy 1bf = im.Flip("characters/roxxy/char_roxxy_01b.png", horizontal=True)
image old_roxxy 1if = im.Flip("characters/roxxy/char_roxxy_01i.png", xoffset=67, horizontal=True)
image old_roxxy 1jf = im.Flip("characters/roxxy/char_roxxy_01j.png", xoffset=67, horizontal=True)
image old_roxxy 1kf = im.Flip("characters/roxxy/char_roxxy_01k.png", xoffset=33, horizontal=True)
image old_roxxy 1lf = im.Flip("characters/roxxy/char_roxxy_01l.png", xoffset=67, horizontal=True)
image old_roxxy 1of = im.Flip("characters/roxxy/char_roxxy_01o.png", xoffset=67, horizontal=True)
image old_roxxy 1mf = im.Flip("characters/roxxy/char_roxxy_01m.png", xoffset=67, horizontal=True)
image old_roxxy 1nf = im.Flip("characters/roxxy/char_roxxy_01n.png", xoffset=67, horizontal=True)
image old_roxxy 2f = im.Flip("characters/roxxy/char_roxxy_02.png", horizontal=True)
image old_roxxy 2bf = im.Flip("characters/roxxy/char_roxxy_02b.png", horizontal=True)
image old_roxxy 2cf = im.Flip("characters/roxxy/char_roxxy_02c.png", horizontal=True)
image old_roxxy 3f = im.Flip("characters/roxxy/char_roxxy_03.png", horizontal=True)
image old_roxxy 3bf = im.Flip("characters/roxxy/char_roxxy_03b.png", horizontal=True)
image old_roxxy 3cf = im.Flip("characters/roxxy/char_roxxy_03c.png", horizontal=True)
image old_roxxy 3df = im.Flip("characters/roxxy/char_roxxy_03d.png", horizontal=True)
image old_roxxy 3ef = im.Flip("characters/roxxy/char_roxxy_03e.png", horizontal=True)
image old_roxxy 4f = im.Flip("characters/roxxy/char_roxxy_04.png", horizontal=True)
image old_roxxy 5f = im.Flip("characters/roxxy/char_roxxy_05.png", horizontal=True)
image old_roxxy 6f = im.Flip("characters/roxxy/char_roxxy_06.png", horizontal=True)
image old_roxxy 7f = im.Flip("characters/roxxy/char_roxxy_07.png", horizontal=True)
image old_roxxy 9f = im.Flip("characters/roxxy/char_roxxy_09.png", horizontal=True)
image old_roxxy 10f = im.Flip("characters/roxxy/char_roxxy_10.png", horizontal=True)
image old_roxxy 11f = im.Flip("characters/roxxy/char_roxxy_11.png", horizontal=True)
image old_roxxy 14f = im.Flip("characters/roxxy/char_roxxy_14.png", horizontal=True)
image old_roxxy 17bf = im.Flip("characters/roxxy/char_roxxy_17b.png", xoffset=67, horizontal=True)
image old_roxxy 17cf = im.Flip("characters/roxxy/char_roxxy_17c.png", xoffset=67, horizontal=True)
image old_roxxy 17df = im.Flip("characters/roxxy/char_roxxy_17d.png", xoffset=67, horizontal=True)
image old_roxxy 17ef = im.Flip("characters/roxxy/char_roxxy_17e.png", xoffset=67, horizontal=True)
image old_roxxy 23f = im.Flip("characters/roxxy/char_roxxy_23.png", horizontal=True)
image old_roxxy 27f = im.Flip("characters/roxxy/char_roxxy_27.png", horizontal=True)
image old_roxxy 28f = im.Flip("characters/roxxy/char_roxxy_28.png", horizontal=True)
image old_roxxy 29f = im.Flip("characters/roxxy/char_roxxy_29.png", horizontal=True)
image old_roxxy 30f = im.Flip("characters/roxxy/char_roxxy_30.png", horizontal=True)
image old_roxxy 31f = im.Flip("characters/roxxy/char_roxxy_31.png", horizontal=True)
image old_roxxy 32f = im.Flip("characters/roxxy/char_roxxy_32.png", xoffset=67, horizontal=True)
image old_roxxy 33f = im.Flip("characters/roxxy/char_roxxy_33.png", xoffset=67, horizontal=True)
image old_roxxy 33bf = im.Flip("characters/roxxy/char_roxxy_33b.png", xoffset=33, horizontal=True)
image old_roxxy 59f = im.Flip("characters/roxxy/char_roxxy_59.png", horizontal=True)
image old_roxxy 66f = im.Flip("characters/roxxy/char_roxxy_66.png", xoffset=110, horizontal=True)
image old_roxxy 68bf = im.Flip("characters/roxxy/char_roxxy_68b.png", xoffset=20, horizontal=True)
image old_roxxy 68cf = im.Flip("characters/roxxy/char_roxxy_68c.png", xoffset=20, horizontal=True)
image old_roxxy 80f = im.Flip("characters/roxxy/char_roxxy_80.png", horizontal=True)
image old_roxxy 81f = im.Flip("characters/roxxy/char_roxxy_81.png", horizontal=True)
image old_roxxy 82f = im.Flip("characters/roxxy/char_roxxy_82.png", horizontal=True)
image old_roxxy 84f = im.Flip("characters/roxxy/char_roxxy_84.png", horizontal=True)
image old_roxxy 106f = im.Flip("characters/roxxy/char_roxxy_106.png", horizontal=True)
image old_roxxy 107f = im.Flip("characters/roxxy/char_roxxy_107.png", horizontal=True)
image old_roxxy 108f = im.Flip("characters/roxxy/char_roxxy_108.png", horizontal=True)

image old_roxxy_wet_undies_f = im.Flip("characters/roxxy/char_roxxy_wet_undies.png", xoffset=91, yoffset=-90, horizontal=True)
image old_roxxy_wet back_f = im.Flip("characters/roxxy/char_roxxy_wet_back.png",xoffset=-207,yoffset=-73, horizontal=True)
image old_roxxy_wet hurt_f = im.Flip("characters/roxxy/char_roxxy_wet_hurt.png",xoffset=92,yoffset=-296, horizontal=True)
image old_roxxy_wet_f = im.Flip("characters/roxxy/char_roxxy_wet.png",xoffset=0,yoffset=-360, horizontal=True)


image old_roxxy bikini 1f = im.Flip("characters/roxxy/char_roxxy_bikini_01.png", horizontal=True)
image old_roxxy bikini 2f = im.Flip("characters/roxxy/char_roxxy_bikini_02.png", horizontal=True)
image old_roxxy bikini 13f = im.Flip("characters/roxxy/char_roxxy_bikini_13.png", horizontal=True)
image old_roxxy bikini 14f = im.Flip("characters/roxxy/char_roxxy_bikini_14.png", horizontal=True)
image old_roxxy bikini 15f = im.Flip("characters/roxxy/char_roxxy_bikini_15.png", horizontal=True)
image old_roxxy bikini 17f = im.Flip("characters/roxxy/char_roxxy_bikini_17.png", horizontal=True)
image old_roxxy bikini 18f = im.Flip("characters/roxxy/char_roxxy_bikini_18.png", horizontal=True)
image old_roxxy bikini 19f = im.Flip("characters/roxxy/char_roxxy_bikini_19.png", horizontal=True)
image old_roxxy bikini 19bf = im.Flip("characters/roxxy/char_roxxy_bikini_19b.png", horizontal=True)
image old_roxxy bikini 20f = im.Flip("characters/roxxy/char_roxxy_bikini_20.png", horizontal=True)
image old_roxxy bikini 21f = im.Flip("characters/roxxy/char_roxxy_bikini_21.png",xoffset=33, horizontal=True)
image old_roxxy bikini 22f = im.Flip("characters/roxxy/char_roxxy_bikini_22.png",xoffset=33, horizontal=True)
image old_roxxy bikini 24f = im.Flip("characters/roxxy/char_roxxy_bikini_24.png",xoffset=33, horizontal=True)

image old_roxxy bikini usa 9f = im.Flip("characters/roxxy/char_roxxy_bikini_usa_09.png", horizontal=True)
image old_roxxy bikini usa 10f = im.Flip("characters/roxxy/char_roxxy_bikini_usa_10.png", horizontal=True)
image old_roxxy bikini usa 11f = im.Flip("characters/roxxy/char_roxxy_bikini_usa_11.png", horizontal=True)
image old_roxxy bikini usa 12f = im.Flip("characters/roxxy/char_roxxy_bikini_usa_12.png",xoffset=14, horizontal=True)
image old_roxxy bikini usa 13f = im.Flip("characters/roxxy/char_roxxy_bikini_usa_13.png",xoffset=14, horizontal=True)
image old_roxxy bikini usa 16f = im.Flip("characters/roxxy/char_roxxy_bikini_usa_16.png",xoffset=14, horizontal=True)
image old_roxxy bikini usa 17f = im.Flip("characters/roxxy/char_roxxy_bikini_usa_17.png",xoffset=14, horizontal=True)
image old_roxxy bikini usa 18f = im.Flip("characters/roxxy/char_roxxy_bikini_usa_18.png",xoffset=14, horizontal=True)

image roxxys_beach_sidef = im.Flip("characters/roxxy/char_roxxy_sex_foursome_side.png", horizontal=True)


image old_crystal 5f = im.Flip("characters/crystal/crystal_05.png", horizontal=True)
image old_crystal 6f = im.Flip("characters/crystal/crystal_06.png", horizontal=True)
image old_crystal 9f = im.Flip("characters/crystal/crystal_09.png", horizontal=True)
image old_crystal 10f = im.Flip("characters/crystal/crystal_10.png", horizontal=True)
image old_crystal 11f = im.Flip("characters/crystal/crystal_11.png", horizontal=True)


image xtra 36f = im.Flip("characters/xtra/char_xtra_36.png", horizontal=True)


image dewitt 1bf = im.Flip("characters/dewitt/char_dewitt_01b.png", horizontal=True)
image dewitt 3bf = im.Flip("characters/dewitt/char_dewitt_03b.png", horizontal=True)
image dewitt 6f = im.Flip("characters/dewitt/char_dewitt_06.png", horizontal=True)
image dewitt 9bf = im.Flip("characters/dewitt/char_dewitt_09b.png", horizontal=True)
image dewitt 9df = im.Flip("characters/dewitt/char_dewitt_09d.png", horizontal=True)
image dewitt 9ff = im.Flip("characters/dewitt/char_dewitt_09f.png", horizontal=True)
image dewitt 10bf = im.Flip("characters/dewitt/char_dewitt_10b.png", horizontal=True)
image dewitt 11bf = im.Flip("characters/dewitt/char_dewitt_11b.png", horizontal=True)
image dewitt 13f = im.Flip("characters/dewitt/char_dewitt_13.png", horizontal=True)
image dewitt 14f = im.Flip("characters/dewitt/char_dewitt_14.png", horizontal=True)
image dewitt 18f = im.Flip("characters/dewitt/char_dewitt_18.png", horizontal=True)
image dewitt 19f = im.Flip("characters/dewitt/char_dewitt_19.png", horizontal=True)
image dewitt 31f = im.Flip("characters/dewitt/char_dewitt_31.png", horizontal=True)
image dewitt 32f = im.Flip("characters/dewitt/char_dewitt_32.png", horizontal=True)
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
