image xray_front_top:
    'xray_front_top_01'
    .3
    'xray_front_top_02'
    .3
    'xray_front_top_03'
    .3
    'xray_front_top_04'
    .3
    'xray_front_top_05'
    .3
    'xray_front_top_06'
    .3
    'xray_front_top_07'
    .3
    'xray_front_top_08'
    .3
    'xray_front_top_09'
    .3
    'xray_front_top_10'
    .3
    'xray_front_top_11'
    .3
    'xray_front_top_12'
    .3
    'xray_front_top_13'
    .3
    'xray_front_top_14'
    .3
    'xray_front_top_15'
    .3
    'xray_front_top_16'
    .3
    'xray_front_top_17'
    .3
    'xray_front_top_18'
    2.
    linear 2.5 alpha 0


image xray_front_under:
    'xray_front_under_01'
    .3
    'xray_front_under_02'
    .3
    'xray_front_under_03'
    .3
    'xray_front_under_04'
    .3
    'xray_front_under_05'
    .3
    'xray_front_under_06'
    .3
    'xray_front_under_07'
    .3
    'xray_front_under_08'
    .3
    'xray_front_under_09'
    .3
    'xray_front_under_10'
    .3
    'xray_front_under_11'
    .3
    'xray_front_under_12'
    .3
    'xray_front_under_13'
    .3
    'xray_front_under_14'
    .3
    'xray_front_under_15'
    .3
    'xray_front_under_16'
    .3
    'xray_front_under_17'
    .3
    'xray_front_under_18'
    2.
    linear 2.5 alpha 0


image xray_left_back:
    'xray_left_back_01'
    .4
    'xray_left_back_02'
    .4
    'xray_left_back_03'
    .4
    'xray_left_back_04'
    .4
    'xray_left_back_05'
    .4
    'xray_left_back_06'
    .4
    'xray_left_back_07'
    .4
    'xray_left_back_08'
    .4
    'xray_left_back_09'
    .4
    'xray_left_back_10'
    .4
    'xray_left_back_11'
    .4
    'xray_left_back_12'
    .4
    'xray_left_back_13'
    .4
    'xray_left_back_14'
    .4
    'xray_left_back_15'
    .4
    'xray_left_back_16'
    .4
    'xray_left_back_17'
    .4
    'xray_left_back_18'
    2
    linear 2.5 alpha 0


image xray_side:
    'xray_side_01'
    .4
    'xray_side_02'
    .4
    'xray_side_03'
    .4
    'xray_side_04'
    .4
    'xray_side_05'
    .4
    'xray_side_06'
    .4
    'xray_side_07'
    .4
    'xray_side_08'
    .4
    'xray_side_09'
    .4
    'xray_side_10'
    .4
    'xray_side_11'
    .4
    'xray_side_12'
    .4
    'xray_side_13'
    .4
    'xray_side_14'
    .4
    'xray_side_15'
    .4
    'xray_side_16'
    .4
    'xray_side_17'
    .4
    'xray_side_18'
    2
    linear 2.5 alpha 0


image xray_under:
    'xray_under_01'
    .3
    'xray_under_02'
    .3
    'xray_under_03'
    .3
    'xray_under_04'
    .3
    'xray_under_05'
    .3
    'xray_under_06'
    .3
    'xray_under_07'
    .3
    'xray_under_08'
    .3
    'xray_under_09'
    .3
    'xray_under_10'
    .3
    'xray_under_11'
    .3
    'xray_under_12'
    .3
    'xray_under_13'
    .3
    'xray_under_14'
    .3
    'xray_under_15'
    .3
    'xray_under_16'
    .3
    'xray_under_17'
    .3
    'xray_under_18'
    2
    linear 2.5 alpha 0
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
